spring.application.name=scheduling-service
server.port=8083

# Configuración de Base de Datos MySQL (Docker)
spring.datasource.url=jdbc:mysql://localhost:3306/db_scheduling_service?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuracion de recordatorios
internal.service.token=TokenSecretoInternoMentoriasG4
user.service.base-url=http://localhost:8081
telegram.bot.token=${TELEGRAM_BOT_TOKEN:}
TELEGRAM_BOT_TOKEN=8828965567:AAFdcLUdej86O-bb2wXNgnHvc9ob45Wb95E
reminders.poll-ms=60000
reminders.window-hours=8
reminders.timezone=America/Santiago

