spring.application.name=user-service

# Puerto del servidor
server.port=8081

# Configuración de la Base de Datos MySQL (Docker)
spring.datasource.url=jdbc:mysql://localhost:3306/db_user_service?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Propiedades para JWT
jwt.secret=ClaveSecretaParaMentoriasG4QueEsMuyLargaYSeguraParaQueNadieLaAdivine
jwt.expiration=86400000

# Token para comunicación interna entre microservicios
internal.service.token=TokenSecretoInternoMentoriasG4

# Configuracion SMTP (usa variables de entorno por seguridad)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SMTP_USERNAME:certimentor@gmail.com}
spring.mail.password=${SMTP_PASSWORD:fktdvaznhepzowpy}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
