spring.application.name=feedback-service
server.port=8084

# Configuración de Base de Datos MySQL (Docker)
spring.datasource.url=jdbc:mysql://localhost:3306/db_feedback_service?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Token para comunicación interna entre microservicios
internal.service.token=TokenSecretoInternoMentoriasG4
